<a href="https://colab.research.google.com/github/itsheeruschamber/PYTHON-FOR-DATA-SCIENCE-PROGRAMS/blob/main/1%2C2programs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

# np.zeros()
zeros_array = np.zeros((2, 3))
print(zeros_array)

# np.arange()
arange_array = np.arange(10)
print(arange_array)

# np.linspace()
linspace_array = np.linspace(1, 26, 3)
print(linspace_array)

# np.indices()
indices_array = np.indices((3, 3))
print(indices_array)

# np.random.rand()
random_float = np.random.rand()
print(random_float)

random_array = np.random.rand(3, 2)
print(random_array)


[[0. 0. 0.]
 [0. 0. 0.]]
[0 1 2 3 4 5 6 7 8 9]
[ 1.  13.5 26. ]
[[[0 0 0]
  [1 1 1]
  [2 2 2]]

 [[0 1 2]
  [0 1 2]
  [0 1 2]]]
0.3403459433899936
[[0.05993916 0.43083766]
 [0.24141806 0.96122891]
 [0.31889696 0.13124175]]


In [4]:
#2 Manipulation of NumPy arrays- Indexing, Slicing, Reshaping, Joining and Splitting.
import numpy as np

# Array (index)
arr = np.array([1, 2, 3, 4])
print(arr[2])
# Output: 3

# Slice
arr = np.array([6, 12, 31, 45, 25, 36, 37, 66])
print(arr[2:5])
# Output: [31 45 25]

# Reshape
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(3, 4)
print(newarr)
# Output:
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]

# Joining
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

# Splitting
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr)


3
[31 45 25]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[1 2 3 4 5 6]
[array([1, 2]), array([3, 4]), array([5, 6])]
